### ISSUE TITLE
Unit tests logic generation

### ISSUE THREAD

**Issue by m4gr3d** [ne0fhyk/mavlink#2]
The java code generator should generate unit tests code as well to validate the generated java mavlink library.

The unit tests should be in the `com.MAVLink.test` package.
For each defined mavlink messages, the automatically generated unit test should do the following:
- Store the binary representation of an instance of the mavlink message in a byte array.
- Use the `Parser.java`class to recreate the corresponding `msg_*` object from the byte array.
- Encode the recreated `msg_*` object to obtain its binary data representation, and store it into another byte array.
- Compare the initial byte array to the `msg_*` object's byte array.

**Comment by TShapinsky** [comment]
I have test generation working, should it be integrated with JUnit?

**Comment by m4gr3d** [comment]
@TShapinsky yea, it should be integrated with junit4.

**Comment by m4gr3d** [comment]
Fixed through pr #8 by @TShapinsky
